// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_state.sql

package store

import (
	"context"
)

const getAgentState = `-- name: GetAgentState :one
SELECT server_id, state_json, updated_at FROM agent_state WHERE server_id = $1
`

func (q *Queries) GetAgentState(ctx context.Context, serverID string) (AgentState, error) {
	row := q.db.QueryRow(ctx, getAgentState, serverID)
	var i AgentState
	err := row.Scan(&i.ServerID, &i.StateJson, &i.UpdatedAt)
	return i, err
}

const upsertAgentState = `-- name: UpsertAgentState :exec
INSERT INTO agent_state (server_id, state_json, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (server_id) DO UPDATE SET
    state_json = EXCLUDED.state_json,
    updated_at = EXCLUDED.updated_at
`

type UpsertAgentStateParams struct {
	ServerID  string `json:"server_id"`
	StateJson []byte `json:"state_json"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertAgentState(ctx context.Context, arg UpsertAgentStateParams) error {
	_, err := q.db.Exec(ctx, upsertAgentState, arg.ServerID, arg.StateJson, arg.UpdatedAt)
	return err
}
