// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRoleBinding = `-- name: DeleteRoleBinding :exec
DELETE FROM role_bindings WHERE id = $1
`

func (q *Queries) DeleteRoleBinding(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRoleBinding, id)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, expires_at, last_seen, ip_address, user_agent, revoked FROM sessions WHERE id = $1 AND revoked = false AND expires_at > $2
`

type GetSessionParams struct {
	ID        string `json:"id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeen,
		&i.IpAddress,
		&i.UserAgent,
		&i.Revoked,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, display_name, password_hash, oidc_subject, disabled, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, oidc_subject, disabled, created_at, last_login_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserRoleBindings = `-- name: GetUserRoleBindings :many
SELECT rb.id, r.name AS role_name, rb.server_id, rb.stack_id
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
WHERE rb.user_id = $1
ORDER BY rb.created_at
`

type GetUserRoleBindingsRow struct {
	ID       string  `json:"id"`
	RoleName string  `json:"role_name"`
	ServerID *string `json:"server_id"`
	StackID  *string `json:"stack_id"`
}

// Returns all role bindings (global + scoped) for a user, including role name and scope columns.
func (q *Queries) GetUserRoleBindings(ctx context.Context, userID string) ([]GetUserRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, getUserRoleBindings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRoleBindingsRow{}
	for rows.Next() {
		var i GetUserRoleBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.ServerID,
			&i.StackID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
WHERE rb.user_id = $1 AND rb.server_id IS NULL AND rb.stack_id IS NULL
`

func (q *Queries) GetUserRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRoleBinding = `-- name: InsertRoleBinding :one
INSERT INTO role_bindings (id, user_id, role_id, server_id, stack_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, role_id, server_id, stack_id, created_at
`

type InsertRoleBindingParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	RoleID    string  `json:"role_id"`
	ServerID  *string `json:"server_id"`
	StackID   *string `json:"stack_id"`
	CreatedAt int64   `json:"created_at"`
}

func (q *Queries) InsertRoleBinding(ctx context.Context, arg InsertRoleBindingParams) (RoleBinding, error) {
	row := q.db.QueryRow(ctx, insertRoleBinding,
		arg.ID,
		arg.UserID,
		arg.RoleID,
		arg.ServerID,
		arg.StackID,
		arg.CreatedAt,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.ServerID,
		&i.StackID,
		&i.CreatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, created_at, expires_at, last_seen, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSessionParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	CreatedAt int64   `json:"created_at"`
	ExpiresAt int64   `json:"expires_at"`
	LastSeen  int64   `json:"last_seen"`
	IpAddress *string `json:"ip_address"`
	UserAgent *string `json:"user_agent"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeen,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, username, display_name, password_hash, disabled, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, display_name, password_hash, oidc_subject, disabled, created_at, last_login_at
`

type InsertUserParams struct {
	ID           string  `json:"id"`
	Username     string  `json:"username"`
	DisplayName  *string `json:"display_name"`
	PasswordHash *string `json:"password_hash"`
	Disabled     bool    `json:"disabled"`
	CreatedAt    int64   `json:"created_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Disabled,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listAllRoleBindings = `-- name: ListAllRoleBindings :many
SELECT id, user_id, role_id, server_id, stack_id, created_at FROM role_bindings ORDER BY created_at
`

func (q *Queries) ListAllRoleBindings(ctx context.Context) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listAllRoleBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.ServerID,
			&i.StackID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsByUser = `-- name: ListRoleBindingsByUser :many
SELECT id, user_id, role_id, server_id, stack_id, created_at FROM role_bindings WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListRoleBindingsByUser(ctx context.Context, userID string) ([]RoleBinding, error) {
	rows, err := q.db.Query(ctx, listRoleBindingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleBinding{}
	for rows.Next() {
		var i RoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.ServerID,
			&i.StackID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, password_hash, oidc_subject, disabled, created_at, last_login_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.OidcSubject,
			&i.Disabled,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked = true WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const setLastLogin = `-- name: SetLastLogin :exec
UPDATE users SET last_login_at = $2 WHERE id = $1
`

type SetLastLoginParams struct {
	ID          string `json:"id"`
	LastLoginAt *int64 `json:"last_login_at"`
}

func (q *Queries) SetLastLogin(ctx context.Context, arg SetLastLoginParams) error {
	_, err := q.db.Exec(ctx, setLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const setUsername = `-- name: SetUsername :one
UPDATE users SET username = $2 WHERE id = $1 RETURNING id, username, display_name, password_hash, oidc_subject, disabled, created_at, last_login_at
`

type SetUsernameParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) SetUsername(ctx context.Context, arg SetUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID       string `json:"id"`
	LastSeen int64  `json:"last_seen"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastSeen)
	return err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users SET display_name = $2 WHERE id = $1 RETURNING id, username, display_name, password_hash, oidc_subject, disabled, created_at, last_login_at
`

type UpdateDisplayNameParams struct {
	ID          string  `json:"id"`
	DisplayName *string `json:"display_name"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET username = $2, display_name = $3, disabled = $4 WHERE id = $1 RETURNING id, username, display_name, password_hash, oidc_subject, disabled, created_at, last_login_at
`

type UpdateUserParams struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	DisplayName *string `json:"display_name"`
	Disabled    bool    `json:"disabled"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Disabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.OidcSubject,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
