// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package store

import (
	"context"
)

const getActiveCertificateForAgent = `-- name: GetActiveCertificateForAgent :one
SELECT serial, agent_id, fingerprint, cert_pem, not_before, not_after, revoked, revoked_at, created_at FROM certificates WHERE agent_id = $1 AND revoked = FALSE ORDER BY not_after DESC LIMIT 1
`

func (q *Queries) GetActiveCertificateForAgent(ctx context.Context, agentID string) (Certificate, error) {
	row := q.db.QueryRow(ctx, getActiveCertificateForAgent, agentID)
	var i Certificate
	err := row.Scan(
		&i.Serial,
		&i.AgentID,
		&i.Fingerprint,
		&i.CertPem,
		&i.NotBefore,
		&i.NotAfter,
		&i.Revoked,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCertificateByFingerprint = `-- name: GetCertificateByFingerprint :one
SELECT serial, agent_id, fingerprint, cert_pem, not_before, not_after, revoked, revoked_at, created_at FROM certificates WHERE fingerprint = $1
`

func (q *Queries) GetCertificateByFingerprint(ctx context.Context, fingerprint string) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByFingerprint, fingerprint)
	var i Certificate
	err := row.Scan(
		&i.Serial,
		&i.AgentID,
		&i.Fingerprint,
		&i.CertPem,
		&i.NotBefore,
		&i.NotAfter,
		&i.Revoked,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentTokenByHash = `-- name: GetEnrollmentTokenByHash :one
SELECT id, token_hash, description, ttl_seconds, max_uses, used_count, created_by, created_at, expires_at, revoked FROM enrollment_tokens WHERE token_hash = $1
`

func (q *Queries) GetEnrollmentTokenByHash(ctx context.Context, tokenHash string) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenByHash, tokenHash)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Description,
		&i.TtlSeconds,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const incrementTokenUsage = `-- name: IncrementTokenUsage :exec
UPDATE enrollment_tokens SET used_count = used_count + 1 WHERE id = $1
`

func (q *Queries) IncrementTokenUsage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementTokenUsage, id)
	return err
}

const insertCertificate = `-- name: InsertCertificate :exec
INSERT INTO certificates (serial, agent_id, fingerprint, cert_pem, not_before, not_after, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCertificateParams struct {
	Serial      string `json:"serial"`
	AgentID     string `json:"agent_id"`
	Fingerprint string `json:"fingerprint"`
	CertPem     string `json:"cert_pem"`
	NotBefore   int64  `json:"not_before"`
	NotAfter    int64  `json:"not_after"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) InsertCertificate(ctx context.Context, arg InsertCertificateParams) error {
	_, err := q.db.Exec(ctx, insertCertificate,
		arg.Serial,
		arg.AgentID,
		arg.Fingerprint,
		arg.CertPem,
		arg.NotBefore,
		arg.NotAfter,
		arg.CreatedAt,
	)
	return err
}

const insertEnrollmentToken = `-- name: InsertEnrollmentToken :one
INSERT INTO enrollment_tokens (id, token_hash, description, ttl_seconds, max_uses, created_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, token_hash, description, ttl_seconds, max_uses, used_count, created_by, created_at, expires_at, revoked
`

type InsertEnrollmentTokenParams struct {
	ID          string  `json:"id"`
	TokenHash   string  `json:"token_hash"`
	Description *string `json:"description"`
	TtlSeconds  int64   `json:"ttl_seconds"`
	MaxUses     int64   `json:"max_uses"`
	CreatedBy   *string `json:"created_by"`
	CreatedAt   int64   `json:"created_at"`
	ExpiresAt   int64   `json:"expires_at"`
}

func (q *Queries) InsertEnrollmentToken(ctx context.Context, arg InsertEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, insertEnrollmentToken,
		arg.ID,
		arg.TokenHash,
		arg.Description,
		arg.TtlSeconds,
		arg.MaxUses,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Description,
		&i.TtlSeconds,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const listEnrollmentTokens = `-- name: ListEnrollmentTokens :many
SELECT id, token_hash, description, ttl_seconds, max_uses, used_count, created_by, created_at, expires_at, revoked FROM enrollment_tokens ORDER BY created_at DESC
`

func (q *Queries) ListEnrollmentTokens(ctx context.Context) ([]EnrollmentToken, error) {
	rows, err := q.db.Query(ctx, listEnrollmentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentToken{}
	for rows.Next() {
		var i EnrollmentToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Description,
			&i.TtlSeconds,
			&i.MaxUses,
			&i.UsedCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCertificate = `-- name: RevokeCertificate :exec
UPDATE certificates SET revoked = TRUE, revoked_at = $1 WHERE serial = $2
`

type RevokeCertificateParams struct {
	RevokedAt *int64 `json:"revoked_at"`
	Serial    string `json:"serial"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) error {
	_, err := q.db.Exec(ctx, revokeCertificate, arg.RevokedAt, arg.Serial)
	return err
}

const revokeEnrollmentToken = `-- name: RevokeEnrollmentToken :exec
UPDATE enrollment_tokens SET revoked = TRUE WHERE id = $1
`

func (q *Queries) RevokeEnrollmentToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeEnrollmentToken, id)
	return err
}
