// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type AgentState struct {
	ServerID  string `json:"server_id"`
	StateJson []byte `json:"state_json"`
	UpdatedAt int64  `json:"updated_at"`
}

type ApiKey struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	Name       string `json:"name"`
	KeyHash    string `json:"key_hash"`
	CreatedAt  int64  `json:"created_at"`
	LastUsedAt *int64 `json:"last_used_at"`
	ExpiresAt  *int64 `json:"expires_at"`
	Revoked    bool   `json:"revoked"`
}

type Assignment struct {
	ID             string  `json:"id"`
	ServerID       string  `json:"server_id"`
	StackID        string  `json:"stack_id"`
	StackVersionID string  `json:"stack_version_id"`
	DesiredStatus  string  `json:"desired_status"`
	AssignedBy     *string `json:"assigned_by"`
	AssignedAt     int64   `json:"assigned_at"`
	EnvValues      []byte  `json:"env_values"`
}

type AuditLog struct {
	ID         int64   `json:"id"`
	Ts         int64   `json:"ts"`
	ActorID    *string `json:"actor_id"`
	ActorName  *string `json:"actor_name"`
	Action     string  `json:"action"`
	TargetType string  `json:"target_type"`
	TargetID   *string `json:"target_id"`
	BeforeJson []byte  `json:"before_json"`
	AfterJson  []byte  `json:"after_json"`
	IpAddress  *string `json:"ip_address"`
	Error      *string `json:"error"`
}

type Ca struct {
	ID        int32  `json:"id"`
	CertPem   string `json:"cert_pem"`
	KeyEnc    []byte `json:"key_enc"`
	CreatedAt int64  `json:"created_at"`
}

type Certificate struct {
	Serial      string `json:"serial"`
	AgentID     string `json:"agent_id"`
	Fingerprint string `json:"fingerprint"`
	CertPem     string `json:"cert_pem"`
	NotBefore   int64  `json:"not_before"`
	NotAfter    int64  `json:"not_after"`
	Revoked     bool   `json:"revoked"`
	RevokedAt   *int64 `json:"revoked_at"`
	CreatedAt   int64  `json:"created_at"`
}

type EnrollmentToken struct {
	ID          string  `json:"id"`
	TokenHash   string  `json:"token_hash"`
	Description *string `json:"description"`
	TtlSeconds  int64   `json:"ttl_seconds"`
	MaxUses     int64   `json:"max_uses"`
	UsedCount   int64   `json:"used_count"`
	CreatedBy   *string `json:"created_by"`
	CreatedAt   int64   `json:"created_at"`
	ExpiresAt   int64   `json:"expires_at"`
	Revoked     bool    `json:"revoked"`
}

type Event struct {
	ID         int64   `json:"id"`
	Ts         int64   `json:"ts"`
	ServerID   *string `json:"server_id"`
	StackID    *string `json:"stack_id"`
	EventType  string  `json:"event_type"`
	Severity   string  `json:"severity"`
	Message    string  `json:"message"`
	DetailJson []byte  `json:"detail_json"`
}

type OidcConfig struct {
	ID              int32  `json:"id"`
	IssuerUrl       string `json:"issuer_url"`
	ClientID        string `json:"client_id"`
	ClientSecretEnc string `json:"client_secret_enc"`
	Scopes          []byte `json:"scopes"`
	ClaimMapping    []byte `json:"claim_mapping"`
	Enabled         bool   `json:"enabled"`
	UpdatedAt       int64  `json:"updated_at"`
	GroupsClaim     string `json:"groups_claim"`
}

type PasswordPolicy struct {
	ID         int32 `json:"id"`
	MinLength  int32 `json:"min_length"`
	SpecialMin int32 `json:"special_min"`
	SpecialMax int32 `json:"special_max"`
	DigitMin   int32 `json:"digit_min"`
	DigitMax   int32 `json:"digit_max"`
	UpperMin   int32 `json:"upper_min"`
	UpperMax   int32 `json:"upper_max"`
	LowerMin   int32 `json:"lower_min"`
	LowerMax   int32 `json:"lower_max"`
	UpdatedAt  int64 `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	TokenHash string  `json:"token_hash"`
	Purpose   string  `json:"purpose"`
	ExpiresAt int64   `json:"expires_at"`
	UsedAt    *int64  `json:"used_at"`
	CreatedAt int64   `json:"created_at"`
	NewEmail  *string `json:"new_email"`
}

type Role struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type RoleBinding struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	RoleID    string  `json:"role_id"`
	ServerID  *string `json:"server_id"`
	StackID   *string `json:"stack_id"`
	CreatedAt int64   `json:"created_at"`
}

type Secret struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Provider    string  `json:"provider"`
	Ciphertext  []byte  `json:"ciphertext"`
	Version     int64   `json:"version"`
	BaoMount    *string `json:"bao_mount"`
	BaoPath     *string `json:"bao_path"`
	BaoKey      *string `json:"bao_key"`
	CreatedBy   *string `json:"created_by"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
}

type SecretBinding struct {
	ID             string  `json:"id"`
	StackVersionID string  `json:"stack_version_id"`
	SecretID       string  `json:"secret_id"`
	ServiceName    string  `json:"service_name"`
	BindingName    string  `json:"binding_name"`
	Target         string  `json:"target"`
	EnvKey         *string `json:"env_key"`
	FilePath       *string `json:"file_path"`
}

type Server struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Hostname      string  `json:"hostname"`
	Arch          string  `json:"arch"`
	Os            string  `json:"os"`
	AgentVersion  *string `json:"agent_version"`
	DockerVersion *string `json:"docker_version"`
	Labels        []byte  `json:"labels"`
	Status        string  `json:"status"`
	LastSeenAt    *int64  `json:"last_seen_at"`
	EnrolledAt    int64   `json:"enrolled_at"`
	DeletedAt     *int64  `json:"deleted_at"`
}

type Session struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	CreatedAt int64   `json:"created_at"`
	ExpiresAt int64   `json:"expires_at"`
	LastSeen  int64   `json:"last_seen"`
	IpAddress *string `json:"ip_address"`
	UserAgent *string `json:"user_agent"`
	Revoked   bool    `json:"revoked"`
}

type SmtpConfig struct {
	ID          int32  `json:"id"`
	Enabled     bool   `json:"enabled"`
	Host        string `json:"host"`
	Port        int32  `json:"port"`
	Username    string `json:"username"`
	PasswordEnc string `json:"password_enc"`
	FromAddress string `json:"from_address"`
	PublicUrl   string `json:"public_url"`
	Starttls    bool   `json:"starttls"`
	UpdatedAt   int64  `json:"updated_at"`
}

type Stack struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Owner       *string `json:"owner"`
	CreatedAt   int64   `json:"created_at"`
	DeletedAt   *int64  `json:"deleted_at"`
}

type StackVersion struct {
	ID          string  `json:"id"`
	StackID     string  `json:"stack_id"`
	Version     int64   `json:"version"`
	ComposeYaml string  `json:"compose_yaml"`
	EnvVarNames []byte  `json:"env_var_names"`
	SecretRefs  []byte  `json:"secret_refs"`
	CreatedBy   *string `json:"created_by"`
	CreatedAt   int64   `json:"created_at"`
}

type User struct {
	ID           string  `json:"id"`
	Username     string  `json:"username"`
	DisplayName  *string `json:"display_name"`
	PasswordHash *string `json:"password_hash"`
	OidcSubject  *string `json:"oidc_subject"`
	Disabled     bool    `json:"disabled"`
	CreatedAt    int64   `json:"created_at"`
	LastLoginAt  *int64  `json:"last_login_at"`
	SsoOnly      bool    `json:"sso_only"`
}
