// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Count enabled users with a global admin role binding, excluding the given user.
	// Used to enforce the invariant that at least one enabled global admin always remains.
	CountEnabledGlobalAdminsExcludingUser(ctx context.Context, id string) (int64, error)
	// Count enabled *local* global admins (can log in without the IdP), excluding the given
	// user. A local admin is not sso_only and has a password set. Used to enforce that at
	// least one local admin always remains when flagging a user sso_only.
	CountEnabledLocalAdminsExcludingUser(ctx context.Context, id string) (int64, error)
	CountSecretBindings(ctx context.Context, secretID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) error
	DeleteAvailableUpdate(ctx context.Context, arg DeleteAvailableUpdateParams) error
	DeleteRoleBinding(ctx context.Context, id string) error
	DeleteSecret(ctx context.Context, id string) error
	DeleteUserByID(ctx context.Context, id string) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetActiveCertificateForAgent(ctx context.Context, agentID string) (Certificate, error)
	GetCertificateByFingerprint(ctx context.Context, fingerprint string) (Certificate, error)
	GetEnrollmentTokenByHash(ctx context.Context, tokenHash string) (EnrollmentToken, error)
	GetLatestStackVersion(ctx context.Context, stackID string) (StackVersion, error)
	GetNextVersionNumber(ctx context.Context, stackID string) (int32, error)
	GetOIDCConfig(ctx context.Context) (OidcConfig, error)
	GetPasswordPolicy(ctx context.Context) (PasswordPolicy, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetRoleBinding(ctx context.Context, id string) (RoleBinding, error)
	GetSMTPConfig(ctx context.Context) (SmtpConfig, error)
	GetSecret(ctx context.Context, id string) (Secret, error)
	GetServer(ctx context.Context, id string) (Server, error)
	GetServerConfig(ctx context.Context) (ServerConfig, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetStack(ctx context.Context, id string) (Stack, error)
	GetStackVersion(ctx context.Context, id string) (StackVersion, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Returns all role bindings (global + scoped) for a user, including role name and scope columns.
	GetUserRoleBindings(ctx context.Context, userID string) ([]GetUserRoleBindingsRow, error)
	GetUserRoles(ctx context.Context, userID string) ([]string, error)
	IncrementTokenUsage(ctx context.Context, id string) error
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCertificate(ctx context.Context, arg InsertCertificateParams) error
	InsertEmailChangeToken(ctx context.Context, arg InsertEmailChangeTokenParams) error
	InsertEnrollmentToken(ctx context.Context, arg InsertEnrollmentTokenParams) (EnrollmentToken, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error
	InsertRoleBinding(ctx context.Context, arg InsertRoleBindingParams) (RoleBinding, error)
	InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error)
	InsertServer(ctx context.Context, arg InsertServerParams) (Server, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertStack(ctx context.Context, arg InsertStackParams) (Stack, error)
	InsertStackVersion(ctx context.Context, arg InsertStackVersionParams) (StackVersion, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	ListAPIKeysByUser(ctx context.Context, userID string) ([]ApiKey, error)
	ListAllAPIKeys(ctx context.Context) ([]ApiKey, error)
	ListAllRoleBindings(ctx context.Context) ([]RoleBinding, error)
	ListAssignmentsForServer(ctx context.Context, serverID string) ([]ListAssignmentsForServerRow, error)
	ListAssignmentsForStack(ctx context.Context, stackID string) ([]Assignment, error)
	ListAuditLog(ctx context.Context, limit int32) ([]AuditLog, error)
	ListAvailableUpdatesForServer(ctx context.Context, serverID string) ([]AvailableUpdate, error)
	ListEnrollmentTokens(ctx context.Context) ([]EnrollmentToken, error)
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error)
	ListEventsFiltered(ctx context.Context, arg ListEventsFilteredParams) ([]Event, error)
	ListRecentEvents(ctx context.Context, limit int32) ([]Event, error)
	ListRoleBindingsByUser(ctx context.Context, userID string) ([]RoleBinding, error)
	ListSecrets(ctx context.Context) ([]ListSecretsRow, error)
	ListServers(ctx context.Context) ([]Server, error)
	ListStackVersions(ctx context.Context, stackID string) ([]StackVersion, error)
	ListStacks(ctx context.Context) ([]Stack, error)
	ListUpdatePolicies(ctx context.Context) ([]UpdatePolicy, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkOfflineServers(ctx context.Context, lastSeenAt *int64) error
	MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) error
	ResolveUpdatePolicy(ctx context.Context, arg ResolveUpdatePolicyParams) (UpdatePolicy, error)
	RevokeAPIKey(ctx context.Context, id string) error
	RevokeAllSessionsForUser(ctx context.Context, userID string) error
	RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) error
	RevokeEnrollmentToken(ctx context.Context, id string) error
	RevokeSession(ctx context.Context, id string) error
	SetLastLogin(ctx context.Context, arg SetLastLoginParams) error
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error
	SetUsername(ctx context.Context, arg SetUsernameParams) (User, error)
	SoftDeleteServer(ctx context.Context, arg SoftDeleteServerParams) error
	SoftDeleteStack(ctx context.Context, arg SoftDeleteStackParams) error
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
	UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error)
	UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertAgentUpdatePolicy(ctx context.Context, arg UpsertAgentUpdatePolicyParams) (UpdatePolicy, error)
	UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (Assignment, error)
	UpsertAvailableUpdate(ctx context.Context, arg UpsertAvailableUpdateParams) (AvailableUpdate, error)
	UpsertFleetUpdatePolicy(ctx context.Context, arg UpsertFleetUpdatePolicyParams) (UpdatePolicy, error)
	UpsertOIDCConfig(ctx context.Context, arg UpsertOIDCConfigParams) (OidcConfig, error)
	UpsertPasswordPolicy(ctx context.Context, arg UpsertPasswordPolicyParams) (PasswordPolicy, error)
	UpsertSMTPConfig(ctx context.Context, arg UpsertSMTPConfigParams) (SmtpConfig, error)
	UpsertServerConfig(ctx context.Context, arg UpsertServerConfigParams) (ServerConfig, error)
}

var _ Querier = (*Queries)(nil)
