// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) error
	GetActiveCertificateForAgent(ctx context.Context, agentID string) (Certificate, error)
	GetCertificateByFingerprint(ctx context.Context, fingerprint string) (Certificate, error)
	GetEnrollmentTokenByHash(ctx context.Context, tokenHash string) (EnrollmentToken, error)
	GetLatestStackVersion(ctx context.Context, stackID string) (StackVersion, error)
	GetNextVersionNumber(ctx context.Context, stackID string) (int32, error)
	GetServer(ctx context.Context, id string) (Server, error)
	GetStack(ctx context.Context, id string) (Stack, error)
	GetStackVersion(ctx context.Context, id string) (StackVersion, error)
	IncrementTokenUsage(ctx context.Context, id string) error
	InsertCertificate(ctx context.Context, arg InsertCertificateParams) error
	InsertEnrollmentToken(ctx context.Context, arg InsertEnrollmentTokenParams) (EnrollmentToken, error)
	InsertServer(ctx context.Context, arg InsertServerParams) (Server, error)
	InsertStack(ctx context.Context, arg InsertStackParams) (Stack, error)
	InsertStackVersion(ctx context.Context, arg InsertStackVersionParams) (StackVersion, error)
	ListAssignmentsForServer(ctx context.Context, serverID string) ([]ListAssignmentsForServerRow, error)
	ListAssignmentsForStack(ctx context.Context, stackID string) ([]Assignment, error)
	ListEnrollmentTokens(ctx context.Context) ([]EnrollmentToken, error)
	ListServers(ctx context.Context) ([]Server, error)
	ListStackVersions(ctx context.Context, stackID string) ([]StackVersion, error)
	ListStacks(ctx context.Context) ([]Stack, error)
	MarkOfflineServers(ctx context.Context, lastSeenAt *int64) error
	RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) error
	RevokeEnrollmentToken(ctx context.Context, id string) error
	SoftDeleteServer(ctx context.Context, arg SoftDeleteServerParams) error
	SoftDeleteStack(ctx context.Context, arg SoftDeleteStackParams) error
	UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error)
	UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error
	UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (Assignment, error)
}

var _ Querier = (*Queries)(nil)
