// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package store

import (
	"context"
)

const deleteAuditLogBefore = `-- name: DeleteAuditLogBefore :execrows
DELETE FROM audit_log WHERE id IN (
    SELECT id FROM audit_log WHERE ts < $1::bigint LIMIT $2
)
`

type DeleteAuditLogBeforeParams struct {
	Cutoff    int64 `json:"cutoff"`
	BatchSize int32 `json:"batch_size"`
}

// Deletes at most batch_size audit entries older than cutoff. Only ever called when an
// admin has explicitly configured an audit retention window.
func (q *Queries) DeleteAuditLogBefore(ctx context.Context, arg DeleteAuditLogBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditLogBefore, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventsBefore = `-- name: DeleteEventsBefore :execrows
DELETE FROM events WHERE id IN (
    SELECT id FROM events WHERE ts < $1::bigint LIMIT $2
)
`

type DeleteEventsBeforeParams struct {
	Cutoff    int64 `json:"cutoff"`
	BatchSize int32 `json:"batch_size"`
}

// Deletes at most batch_size events older than cutoff. Bounded so the retention job
// never holds a long lock; the caller loops until a batch comes back short.
func (q *Queries) DeleteEventsBefore(ctx context.Context, arg DeleteEventsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventsBefore, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE id IN (
    SELECT id FROM sessions WHERE expires_at < $1::bigint LIMIT $2
)
`

type DeleteExpiredSessionsParams struct {
	Cutoff    int64 `json:"cutoff"`
	BatchSize int32 `json:"batch_size"`
}

// Deletes at most batch_size sessions whose expiry has passed. Expired rows can no longer
// authenticate anyone (GetSession filters on expires_at), so they are pure ballast.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
