// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package store

import (
	"context"
)

const countSecretBindings = `-- name: CountSecretBindings :one
SELECT COUNT(*) FROM secret_bindings WHERE secret_id = $1
`

func (q *Queries) CountSecretBindings(ctx context.Context, secretID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretBindings, secretID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, name, description, provider, ciphertext, version, bao_mount, bao_path, bao_key, created_by, created_at, updated_at FROM secrets WHERE id = $1
`

func (q *Queries) GetSecret(ctx context.Context, id string) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Ciphertext,
		&i.Version,
		&i.BaoMount,
		&i.BaoPath,
		&i.BaoKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (ts, actor_id, actor_name, action, target_type, target_id, ip_address, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	Ts         int64   `json:"ts"`
	ActorID    *string `json:"actor_id"`
	ActorName  *string `json:"actor_name"`
	Action     string  `json:"action"`
	TargetType string  `json:"target_type"`
	TargetID   *string `json:"target_id"`
	IpAddress  *string `json:"ip_address"`
	Error      *string `json:"error"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Ts,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.IpAddress,
		arg.Error,
	)
	return err
}

const insertSecret = `-- name: InsertSecret :one
INSERT INTO secrets (id, name, description, provider, ciphertext, version, bao_mount, bao_path, bao_key, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, description, provider, ciphertext, version, bao_mount, bao_path, bao_key, created_by, created_at, updated_at
`

type InsertSecretParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Provider    string  `json:"provider"`
	Ciphertext  []byte  `json:"ciphertext"`
	Version     int64   `json:"version"`
	BaoMount    *string `json:"bao_mount"`
	BaoPath     *string `json:"bao_path"`
	BaoKey      *string `json:"bao_key"`
	CreatedBy   *string `json:"created_by"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, insertSecret,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Provider,
		arg.Ciphertext,
		arg.Version,
		arg.BaoMount,
		arg.BaoPath,
		arg.BaoKey,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Ciphertext,
		&i.Version,
		&i.BaoMount,
		&i.BaoPath,
		&i.BaoKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, ts, actor_id, actor_name, action, target_type, target_id, before_json, after_json, ip_address, error FROM audit_log ORDER BY ts DESC LIMIT $1
`

func (q *Queries) ListAuditLog(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.IpAddress,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, name, description, provider, version, bao_mount, bao_path, bao_key, created_by, created_at, updated_at
FROM secrets ORDER BY name
`

type ListSecretsRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Provider    string  `json:"provider"`
	Version     int64   `json:"version"`
	BaoMount    *string `json:"bao_mount"`
	BaoPath     *string `json:"bao_path"`
	BaoKey      *string `json:"bao_key"`
	CreatedBy   *string `json:"created_by"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
}

func (q *Queries) ListSecrets(ctx context.Context) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.Version,
			&i.BaoMount,
			&i.BaoPath,
			&i.BaoKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets
SET description = $2, ciphertext = $3, version = version + 1,
    bao_mount = $4, bao_path = $5, bao_key = $6, updated_at = $7
WHERE id = $1
RETURNING id, name, description, provider, ciphertext, version, bao_mount, bao_path, bao_key, created_by, created_at, updated_at
`

type UpdateSecretParams struct {
	ID          string  `json:"id"`
	Description *string `json:"description"`
	Ciphertext  []byte  `json:"ciphertext"`
	BaoMount    *string `json:"bao_mount"`
	BaoPath     *string `json:"bao_path"`
	BaoKey      *string `json:"bao_key"`
	UpdatedAt   int64   `json:"updated_at"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret,
		arg.ID,
		arg.Description,
		arg.Ciphertext,
		arg.BaoMount,
		arg.BaoPath,
		arg.BaoKey,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.Ciphertext,
		&i.Version,
		&i.BaoMount,
		&i.BaoPath,
		&i.BaoKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
