// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_config.sql

package store

import (
	"context"
)

const getServerConfig = `-- name: GetServerConfig :one
SELECT id, public_url, updated_at FROM server_config LIMIT 1
`

func (q *Queries) GetServerConfig(ctx context.Context) (ServerConfig, error) {
	row := q.db.QueryRow(ctx, getServerConfig)
	var i ServerConfig
	err := row.Scan(&i.ID, &i.PublicUrl, &i.UpdatedAt)
	return i, err
}

const upsertServerConfig = `-- name: UpsertServerConfig :one
INSERT INTO server_config (id, public_url, updated_at)
VALUES (1, $1, $2)
ON CONFLICT (id) DO UPDATE SET
    public_url = excluded.public_url,
    updated_at = excluded.updated_at
RETURNING id, public_url, updated_at
`

type UpsertServerConfigParams struct {
	PublicUrl string `json:"public_url"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertServerConfig(ctx context.Context, arg UpsertServerConfigParams) (ServerConfig, error) {
	row := q.db.QueryRow(ctx, upsertServerConfig, arg.PublicUrl, arg.UpdatedAt)
	var i ServerConfig
	err := row.Scan(&i.ID, &i.PublicUrl, &i.UpdatedAt)
	return i, err
}
