// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package store

import (
	"context"
)

const getServer = `-- name: GetServer :one
SELECT id, name, hostname, arch, os, agent_version, docker_version, labels, status, last_seen_at, enrolled_at, deleted_at FROM servers WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetServer(ctx context.Context, id string) (Server, error) {
	row := q.db.QueryRow(ctx, getServer, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Arch,
		&i.Os,
		&i.AgentVersion,
		&i.DockerVersion,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.EnrolledAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertServer = `-- name: InsertServer :one
INSERT INTO servers (id, name, hostname, arch, os, agent_version, docker_version, labels, status, enrolled_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'offline', $9)
RETURNING id, name, hostname, arch, os, agent_version, docker_version, labels, status, last_seen_at, enrolled_at, deleted_at
`

type InsertServerParams struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Hostname      string  `json:"hostname"`
	Arch          string  `json:"arch"`
	Os            string  `json:"os"`
	AgentVersion  *string `json:"agent_version"`
	DockerVersion *string `json:"docker_version"`
	Labels        []byte  `json:"labels"`
	EnrolledAt    int64   `json:"enrolled_at"`
}

func (q *Queries) InsertServer(ctx context.Context, arg InsertServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, insertServer,
		arg.ID,
		arg.Name,
		arg.Hostname,
		arg.Arch,
		arg.Os,
		arg.AgentVersion,
		arg.DockerVersion,
		arg.Labels,
		arg.EnrolledAt,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Arch,
		&i.Os,
		&i.AgentVersion,
		&i.DockerVersion,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.EnrolledAt,
		&i.DeletedAt,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, name, hostname, arch, os, agent_version, docker_version, labels, status, last_seen_at, enrolled_at, deleted_at FROM servers WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.Arch,
			&i.Os,
			&i.AgentVersion,
			&i.DockerVersion,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.EnrolledAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOfflineServers = `-- name: MarkOfflineServers :exec
UPDATE servers SET status = 'offline'
WHERE status = 'online' AND last_seen_at < $1
`

func (q *Queries) MarkOfflineServers(ctx context.Context, lastSeenAt *int64) error {
	_, err := q.db.Exec(ctx, markOfflineServers, lastSeenAt)
	return err
}

const softDeleteServer = `-- name: SoftDeleteServer :exec
UPDATE servers SET deleted_at = $1 WHERE id = $2
`

type SoftDeleteServerParams struct {
	DeletedAt *int64 `json:"deleted_at"`
	ID        string `json:"id"`
}

func (q *Queries) SoftDeleteServer(ctx context.Context, arg SoftDeleteServerParams) error {
	_, err := q.db.Exec(ctx, softDeleteServer, arg.DeletedAt, arg.ID)
	return err
}

const updateServer = `-- name: UpdateServer :one
UPDATE servers SET name = $1, labels = $2 WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, hostname, arch, os, agent_version, docker_version, labels, status, last_seen_at, enrolled_at, deleted_at
`

type UpdateServerParams struct {
	Name   string `json:"name"`
	Labels []byte `json:"labels"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServer, arg.Name, arg.Labels, arg.ID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.Arch,
		&i.Os,
		&i.AgentVersion,
		&i.DockerVersion,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.EnrolledAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateServerStatus = `-- name: UpdateServerStatus :exec
UPDATE servers SET status = $1, last_seen_at = $2 WHERE id = $3
`

type UpdateServerStatusParams struct {
	Status     string `json:"status"`
	LastSeenAt *int64 `json:"last_seen_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error {
	_, err := q.db.Exec(ctx, updateServerStatus, arg.Status, arg.LastSeenAt, arg.ID)
	return err
}
