// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smtp.sql

package store

import (
	"context"
)

const getPasswordPolicy = `-- name: GetPasswordPolicy :one
SELECT id, min_length, special_min, special_max, digit_min, digit_max, upper_min, upper_max, lower_min, lower_max, updated_at FROM password_policy LIMIT 1
`

func (q *Queries) GetPasswordPolicy(ctx context.Context) (PasswordPolicy, error) {
	row := q.db.QueryRow(ctx, getPasswordPolicy)
	var i PasswordPolicy
	err := row.Scan(
		&i.ID,
		&i.MinLength,
		&i.SpecialMin,
		&i.SpecialMax,
		&i.DigitMin,
		&i.DigitMax,
		&i.UpperMin,
		&i.UpperMax,
		&i.LowerMin,
		&i.LowerMax,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, purpose, expires_at, used_at, created_at, new_email FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.NewEmail,
	)
	return i, err
}

const getSMTPConfig = `-- name: GetSMTPConfig :one
SELECT id, enabled, host, port, username, password_enc, from_address, public_url, starttls, updated_at FROM smtp_config LIMIT 1
`

func (q *Queries) GetSMTPConfig(ctx context.Context) (SmtpConfig, error) {
	row := q.db.QueryRow(ctx, getSMTPConfig)
	var i SmtpConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromAddress,
		&i.PublicUrl,
		&i.Starttls,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEmailChangeToken = `-- name: InsertEmailChangeToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, purpose, new_email, expires_at, created_at)
VALUES ($1, $2, $3, 'email_change', $4, $5, $6)
`

type InsertEmailChangeTokenParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	TokenHash string  `json:"token_hash"`
	NewEmail  *string `json:"new_email"`
	ExpiresAt int64   `json:"expires_at"`
	CreatedAt int64   `json:"created_at"`
}

func (q *Queries) InsertEmailChangeToken(ctx context.Context, arg InsertEmailChangeTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailChangeToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.NewEmail,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, purpose, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPasswordResetTokenParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	Purpose   string `json:"purpose"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens SET used_at = $2 WHERE id = $1
`

type MarkPasswordResetTokenUsedParams struct {
	ID     string `json:"id"`
	UsedAt *int64 `json:"used_at"`
}

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, arg.ID, arg.UsedAt)
	return err
}

const upsertPasswordPolicy = `-- name: UpsertPasswordPolicy :one
INSERT INTO password_policy (id, min_length, special_min, special_max, digit_min, digit_max, upper_min, upper_max, lower_min, lower_max, updated_at)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    min_length  = excluded.min_length,
    special_min = excluded.special_min,
    special_max = excluded.special_max,
    digit_min   = excluded.digit_min,
    digit_max   = excluded.digit_max,
    upper_min   = excluded.upper_min,
    upper_max   = excluded.upper_max,
    lower_min   = excluded.lower_min,
    lower_max   = excluded.lower_max,
    updated_at  = excluded.updated_at
RETURNING id, min_length, special_min, special_max, digit_min, digit_max, upper_min, upper_max, lower_min, lower_max, updated_at
`

type UpsertPasswordPolicyParams struct {
	MinLength  int32 `json:"min_length"`
	SpecialMin int32 `json:"special_min"`
	SpecialMax int32 `json:"special_max"`
	DigitMin   int32 `json:"digit_min"`
	DigitMax   int32 `json:"digit_max"`
	UpperMin   int32 `json:"upper_min"`
	UpperMax   int32 `json:"upper_max"`
	LowerMin   int32 `json:"lower_min"`
	LowerMax   int32 `json:"lower_max"`
	UpdatedAt  int64 `json:"updated_at"`
}

func (q *Queries) UpsertPasswordPolicy(ctx context.Context, arg UpsertPasswordPolicyParams) (PasswordPolicy, error) {
	row := q.db.QueryRow(ctx, upsertPasswordPolicy,
		arg.MinLength,
		arg.SpecialMin,
		arg.SpecialMax,
		arg.DigitMin,
		arg.DigitMax,
		arg.UpperMin,
		arg.UpperMax,
		arg.LowerMin,
		arg.LowerMax,
		arg.UpdatedAt,
	)
	var i PasswordPolicy
	err := row.Scan(
		&i.ID,
		&i.MinLength,
		&i.SpecialMin,
		&i.SpecialMax,
		&i.DigitMin,
		&i.DigitMax,
		&i.UpperMin,
		&i.UpperMax,
		&i.LowerMin,
		&i.LowerMax,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSMTPConfig = `-- name: UpsertSMTPConfig :one
INSERT INTO smtp_config (id, enabled, host, port, username, password_enc, from_address, public_url, starttls, updated_at)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    enabled      = excluded.enabled,
    host         = excluded.host,
    port         = excluded.port,
    username     = excluded.username,
    password_enc = excluded.password_enc,
    from_address = excluded.from_address,
    public_url   = excluded.public_url,
    starttls     = excluded.starttls,
    updated_at   = excluded.updated_at
RETURNING id, enabled, host, port, username, password_enc, from_address, public_url, starttls, updated_at
`

type UpsertSMTPConfigParams struct {
	Enabled     bool   `json:"enabled"`
	Host        string `json:"host"`
	Port        int32  `json:"port"`
	Username    string `json:"username"`
	PasswordEnc string `json:"password_enc"`
	FromAddress string `json:"from_address"`
	PublicUrl   string `json:"public_url"`
	Starttls    bool   `json:"starttls"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) UpsertSMTPConfig(ctx context.Context, arg UpsertSMTPConfigParams) (SmtpConfig, error) {
	row := q.db.QueryRow(ctx, upsertSMTPConfig,
		arg.Enabled,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEnc,
		arg.FromAddress,
		arg.PublicUrl,
		arg.Starttls,
		arg.UpdatedAt,
	)
	var i SmtpConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromAddress,
		&i.PublicUrl,
		&i.Starttls,
		&i.UpdatedAt,
	)
	return i, err
}
