// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stacks.sql

package store

import (
	"context"
)

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments WHERE server_id = $1 AND stack_id = $2
`

type DeleteAssignmentParams struct {
	ServerID string `json:"server_id"`
	StackID  string `json:"stack_id"`
}

func (q *Queries) DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteAssignment, arg.ServerID, arg.StackID)
	return err
}

const getLatestStackVersion = `-- name: GetLatestStackVersion :one
SELECT id, stack_id, version, compose_yaml, env_var_names, secret_refs, created_by, created_at FROM stack_versions WHERE stack_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestStackVersion(ctx context.Context, stackID string) (StackVersion, error) {
	row := q.db.QueryRow(ctx, getLatestStackVersion, stackID)
	var i StackVersion
	err := row.Scan(
		&i.ID,
		&i.StackID,
		&i.Version,
		&i.ComposeYaml,
		&i.EnvVarNames,
		&i.SecretRefs,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getNextVersionNumber = `-- name: GetNextVersionNumber :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version FROM stack_versions WHERE stack_id = $1
`

func (q *Queries) GetNextVersionNumber(ctx context.Context, stackID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextVersionNumber, stackID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const getStack = `-- name: GetStack :one
SELECT id, name, description, owner, created_at, deleted_at FROM stacks WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStack(ctx context.Context, id string) (Stack, error) {
	row := q.db.QueryRow(ctx, getStack, id)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Owner,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStackVersion = `-- name: GetStackVersion :one
SELECT id, stack_id, version, compose_yaml, env_var_names, secret_refs, created_by, created_at FROM stack_versions WHERE id = $1
`

func (q *Queries) GetStackVersion(ctx context.Context, id string) (StackVersion, error) {
	row := q.db.QueryRow(ctx, getStackVersion, id)
	var i StackVersion
	err := row.Scan(
		&i.ID,
		&i.StackID,
		&i.Version,
		&i.ComposeYaml,
		&i.EnvVarNames,
		&i.SecretRefs,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertStack = `-- name: InsertStack :one
INSERT INTO stacks (id, name, description, owner, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, owner, created_at, deleted_at
`

type InsertStackParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Owner       *string `json:"owner"`
	CreatedAt   int64   `json:"created_at"`
}

func (q *Queries) InsertStack(ctx context.Context, arg InsertStackParams) (Stack, error) {
	row := q.db.QueryRow(ctx, insertStack,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Owner,
		arg.CreatedAt,
	)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Owner,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertStackVersion = `-- name: InsertStackVersion :one
INSERT INTO stack_versions (id, stack_id, version, compose_yaml, env_var_names, secret_refs, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, stack_id, version, compose_yaml, env_var_names, secret_refs, created_by, created_at
`

type InsertStackVersionParams struct {
	ID          string  `json:"id"`
	StackID     string  `json:"stack_id"`
	Version     int64   `json:"version"`
	ComposeYaml string  `json:"compose_yaml"`
	EnvVarNames []byte  `json:"env_var_names"`
	SecretRefs  []byte  `json:"secret_refs"`
	CreatedBy   *string `json:"created_by"`
	CreatedAt   int64   `json:"created_at"`
}

func (q *Queries) InsertStackVersion(ctx context.Context, arg InsertStackVersionParams) (StackVersion, error) {
	row := q.db.QueryRow(ctx, insertStackVersion,
		arg.ID,
		arg.StackID,
		arg.Version,
		arg.ComposeYaml,
		arg.EnvVarNames,
		arg.SecretRefs,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i StackVersion
	err := row.Scan(
		&i.ID,
		&i.StackID,
		&i.Version,
		&i.ComposeYaml,
		&i.EnvVarNames,
		&i.SecretRefs,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAssignmentsForServer = `-- name: ListAssignmentsForServer :many
SELECT a.id, a.server_id, a.stack_id, a.stack_version_id, a.desired_status, a.assigned_by, a.assigned_at, a.env_values, sv.compose_yaml, sv.secret_refs
FROM assignments a
JOIN stack_versions sv ON sv.id = a.stack_version_id
WHERE a.server_id = $1
`

type ListAssignmentsForServerRow struct {
	ID             string  `json:"id"`
	ServerID       string  `json:"server_id"`
	StackID        string  `json:"stack_id"`
	StackVersionID string  `json:"stack_version_id"`
	DesiredStatus  string  `json:"desired_status"`
	AssignedBy     *string `json:"assigned_by"`
	AssignedAt     int64   `json:"assigned_at"`
	EnvValues      []byte  `json:"env_values"`
	ComposeYaml    string  `json:"compose_yaml"`
	SecretRefs     []byte  `json:"secret_refs"`
}

func (q *Queries) ListAssignmentsForServer(ctx context.Context, serverID string) ([]ListAssignmentsForServerRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsForServerRow{}
	for rows.Next() {
		var i ListAssignmentsForServerRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.StackID,
			&i.StackVersionID,
			&i.DesiredStatus,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.EnvValues,
			&i.ComposeYaml,
			&i.SecretRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsForStack = `-- name: ListAssignmentsForStack :many
SELECT id, server_id, stack_id, stack_version_id, desired_status, assigned_by, assigned_at, env_values FROM assignments WHERE stack_id = $1
`

func (q *Queries) ListAssignmentsForStack(ctx context.Context, stackID string) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsForStack, stackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.StackID,
			&i.StackVersionID,
			&i.DesiredStatus,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.EnvValues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStackVersions = `-- name: ListStackVersions :many
SELECT id, stack_id, version, compose_yaml, env_var_names, secret_refs, created_by, created_at FROM stack_versions WHERE stack_id = $1 ORDER BY version DESC
`

func (q *Queries) ListStackVersions(ctx context.Context, stackID string) ([]StackVersion, error) {
	rows, err := q.db.Query(ctx, listStackVersions, stackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StackVersion{}
	for rows.Next() {
		var i StackVersion
		if err := rows.Scan(
			&i.ID,
			&i.StackID,
			&i.Version,
			&i.ComposeYaml,
			&i.EnvVarNames,
			&i.SecretRefs,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStacks = `-- name: ListStacks :many
SELECT id, name, description, owner, created_at, deleted_at FROM stacks WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListStacks(ctx context.Context) ([]Stack, error) {
	rows, err := q.db.Query(ctx, listStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stack{}
	for rows.Next() {
		var i Stack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Owner,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStack = `-- name: SoftDeleteStack :exec
UPDATE stacks SET deleted_at = $1 WHERE id = $2
`

type SoftDeleteStackParams struct {
	DeletedAt *int64 `json:"deleted_at"`
	ID        string `json:"id"`
}

func (q *Queries) SoftDeleteStack(ctx context.Context, arg SoftDeleteStackParams) error {
	_, err := q.db.Exec(ctx, softDeleteStack, arg.DeletedAt, arg.ID)
	return err
}

const upsertAssignment = `-- name: UpsertAssignment :one
INSERT INTO assignments (id, server_id, stack_id, stack_version_id, desired_status, assigned_by, assigned_at, env_values)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(server_id, stack_id) DO UPDATE SET
    stack_version_id = excluded.stack_version_id,
    desired_status   = excluded.desired_status,
    assigned_by      = excluded.assigned_by,
    assigned_at      = excluded.assigned_at,
    env_values       = excluded.env_values
RETURNING id, server_id, stack_id, stack_version_id, desired_status, assigned_by, assigned_at, env_values
`

type UpsertAssignmentParams struct {
	ID             string  `json:"id"`
	ServerID       string  `json:"server_id"`
	StackID        string  `json:"stack_id"`
	StackVersionID string  `json:"stack_version_id"`
	DesiredStatus  string  `json:"desired_status"`
	AssignedBy     *string `json:"assigned_by"`
	AssignedAt     int64   `json:"assigned_at"`
	EnvValues      []byte  `json:"env_values"`
}

func (q *Queries) UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, upsertAssignment,
		arg.ID,
		arg.ServerID,
		arg.StackID,
		arg.StackVersionID,
		arg.DesiredStatus,
		arg.AssignedBy,
		arg.AssignedAt,
		arg.EnvValues,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.StackID,
		&i.StackVersionID,
		&i.DesiredStatus,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.EnvValues,
	)
	return i, err
}
