// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updates.sql

package store

import (
	"context"
)

const deleteAvailableUpdate = `-- name: DeleteAvailableUpdate :exec
DELETE FROM available_updates WHERE server_id = $1 AND layer = $2
`

type DeleteAvailableUpdateParams struct {
	ServerID string `json:"server_id"`
	Layer    string `json:"layer"`
}

func (q *Queries) DeleteAvailableUpdate(ctx context.Context, arg DeleteAvailableUpdateParams) error {
	_, err := q.db.Exec(ctx, deleteAvailableUpdate, arg.ServerID, arg.Layer)
	return err
}

const listAvailableUpdatesForServer = `-- name: ListAvailableUpdatesForServer :many
SELECT server_id, layer, current_version, candidate_version, detail, detected_at FROM available_updates WHERE server_id = $1 ORDER BY layer
`

func (q *Queries) ListAvailableUpdatesForServer(ctx context.Context, serverID string) ([]AvailableUpdate, error) {
	rows, err := q.db.Query(ctx, listAvailableUpdatesForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableUpdate{}
	for rows.Next() {
		var i AvailableUpdate
		if err := rows.Scan(
			&i.ServerID,
			&i.Layer,
			&i.CurrentVersion,
			&i.CandidateVersion,
			&i.Detail,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdatePolicies = `-- name: ListUpdatePolicies :many
SELECT server_id, layer, mode, window_cron, auto_reboot, updated_at FROM update_policies ORDER BY server_id NULLS FIRST, layer
`

func (q *Queries) ListUpdatePolicies(ctx context.Context) ([]UpdatePolicy, error) {
	rows, err := q.db.Query(ctx, listUpdatePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdatePolicy{}
	for rows.Next() {
		var i UpdatePolicy
		if err := rows.Scan(
			&i.ServerID,
			&i.Layer,
			&i.Mode,
			&i.WindowCron,
			&i.AutoReboot,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUpdatePolicy = `-- name: ResolveUpdatePolicy :one
SELECT server_id, layer, mode, window_cron, auto_reboot, updated_at FROM update_policies
WHERE layer = $2 AND (server_id = $1 OR server_id IS NULL)
ORDER BY (server_id IS NULL)
LIMIT 1
`

type ResolveUpdatePolicyParams struct {
	ServerID *string `json:"server_id"`
	Layer    string  `json:"layer"`
}

func (q *Queries) ResolveUpdatePolicy(ctx context.Context, arg ResolveUpdatePolicyParams) (UpdatePolicy, error) {
	row := q.db.QueryRow(ctx, resolveUpdatePolicy, arg.ServerID, arg.Layer)
	var i UpdatePolicy
	err := row.Scan(
		&i.ServerID,
		&i.Layer,
		&i.Mode,
		&i.WindowCron,
		&i.AutoReboot,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentUpdatePolicy = `-- name: UpsertAgentUpdatePolicy :one
INSERT INTO update_policies (server_id, layer, mode, window_cron, auto_reboot, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (server_id, layer) WHERE server_id IS NOT NULL
DO UPDATE SET mode = EXCLUDED.mode, window_cron = EXCLUDED.window_cron,
              auto_reboot = EXCLUDED.auto_reboot, updated_at = EXCLUDED.updated_at
RETURNING server_id, layer, mode, window_cron, auto_reboot, updated_at
`

type UpsertAgentUpdatePolicyParams struct {
	ServerID   *string `json:"server_id"`
	Layer      string  `json:"layer"`
	Mode       string  `json:"mode"`
	WindowCron *string `json:"window_cron"`
	AutoReboot bool    `json:"auto_reboot"`
	UpdatedAt  int64   `json:"updated_at"`
}

func (q *Queries) UpsertAgentUpdatePolicy(ctx context.Context, arg UpsertAgentUpdatePolicyParams) (UpdatePolicy, error) {
	row := q.db.QueryRow(ctx, upsertAgentUpdatePolicy,
		arg.ServerID,
		arg.Layer,
		arg.Mode,
		arg.WindowCron,
		arg.AutoReboot,
		arg.UpdatedAt,
	)
	var i UpdatePolicy
	err := row.Scan(
		&i.ServerID,
		&i.Layer,
		&i.Mode,
		&i.WindowCron,
		&i.AutoReboot,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAvailableUpdate = `-- name: UpsertAvailableUpdate :one
INSERT INTO available_updates (server_id, layer, current_version, candidate_version, detail, detected_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (server_id, layer)
DO UPDATE SET current_version = EXCLUDED.current_version,
              candidate_version = EXCLUDED.candidate_version,
              detail = EXCLUDED.detail, detected_at = EXCLUDED.detected_at
RETURNING server_id, layer, current_version, candidate_version, detail, detected_at
`

type UpsertAvailableUpdateParams struct {
	ServerID         string `json:"server_id"`
	Layer            string `json:"layer"`
	CurrentVersion   string `json:"current_version"`
	CandidateVersion string `json:"candidate_version"`
	Detail           []byte `json:"detail"`
	DetectedAt       int64  `json:"detected_at"`
}

func (q *Queries) UpsertAvailableUpdate(ctx context.Context, arg UpsertAvailableUpdateParams) (AvailableUpdate, error) {
	row := q.db.QueryRow(ctx, upsertAvailableUpdate,
		arg.ServerID,
		arg.Layer,
		arg.CurrentVersion,
		arg.CandidateVersion,
		arg.Detail,
		arg.DetectedAt,
	)
	var i AvailableUpdate
	err := row.Scan(
		&i.ServerID,
		&i.Layer,
		&i.CurrentVersion,
		&i.CandidateVersion,
		&i.Detail,
		&i.DetectedAt,
	)
	return i, err
}

const upsertFleetUpdatePolicy = `-- name: UpsertFleetUpdatePolicy :one
INSERT INTO update_policies (server_id, layer, mode, window_cron, auto_reboot, updated_at)
VALUES (NULL, $1, $2, $3, $4, $5)
ON CONFLICT (layer) WHERE server_id IS NULL
DO UPDATE SET mode = EXCLUDED.mode, window_cron = EXCLUDED.window_cron,
              auto_reboot = EXCLUDED.auto_reboot, updated_at = EXCLUDED.updated_at
RETURNING server_id, layer, mode, window_cron, auto_reboot, updated_at
`

type UpsertFleetUpdatePolicyParams struct {
	Layer      string  `json:"layer"`
	Mode       string  `json:"mode"`
	WindowCron *string `json:"window_cron"`
	AutoReboot bool    `json:"auto_reboot"`
	UpdatedAt  int64   `json:"updated_at"`
}

func (q *Queries) UpsertFleetUpdatePolicy(ctx context.Context, arg UpsertFleetUpdatePolicyParams) (UpdatePolicy, error) {
	row := q.db.QueryRow(ctx, upsertFleetUpdatePolicy,
		arg.Layer,
		arg.Mode,
		arg.WindowCron,
		arg.AutoReboot,
		arg.UpdatedAt,
	)
	var i UpdatePolicy
	err := row.Scan(
		&i.ServerID,
		&i.Layer,
		&i.Mode,
		&i.WindowCron,
		&i.AutoReboot,
		&i.UpdatedAt,
	)
	return i, err
}
